import type { Crop } from "./types";

/**
 * Crop knowledge base. Agronomic ranges are compiled from FAO crop water
 * requirement tables (FAO-56) and common extension-service guidance.
 */
export const CROPS: Crop[] = [
  {
    id: "rice",
    name: "Rice",
    emoji: "🌾",
    category: "Cereal",
    tempRange: [20, 37],
    humidityRange: [60, 95],
    rainRange: [900, 2500],
    phRange: [5.0, 7.5],
    soils: ["clay", "alluvial", "loamy", "silt"],
    n: 100,
    p: 50,
    k: 50,
    durationDays: 120,
    waterMmPerSeason: 1200,
    yieldTonPerHa: 4.5,
    pricePerTon: 280,
    costPerHa: 620,
    difficulty: 3,
    diseaseResistance: 55,
    marketDemand: 92,
    exportDemand: 70,
    carbonPerHa: 4.2,
    nitrogenFixing: false,
    plantingMonths: [5, 6, 7],
    diseases: [
      {
        name: "Rice blast",
        trigger: "humid",
        symptoms: "Diamond-shaped grey lesions on leaves, neck rot.",
        prevention: "Resistant varieties, balanced nitrogen, wider spacing.",
        treatment: "Tricyclazole or azoxystrobin at boot stage.",
      },
      {
        name: "Bacterial leaf blight",
        trigger: "wet",
        symptoms: "Yellow wavy leaf margins drying inwards.",
        prevention: "Avoid excess N, drain fields periodically.",
        treatment: "Copper oxychloride + streptocycline spray.",
      },
    ],
    pests: ["Stem borer", "Brown planthopper", "Leaf folder"],
    rotateAfter: ["Green gram", "Groundnut"],
    rotateBefore: ["Chickpea", "Mustard"],
    irrigation: "Flood / alternate wetting and drying",
    notes: "Puddled transplanting gives best establishment in heavy soils.",
  },
  {
    id: "wheat",
    name: "Wheat",
    emoji: "🌾",
    category: "Cereal",
    tempRange: [10, 26],
    humidityRange: [40, 75],
    rainRange: [350, 900],
    phRange: [6.0, 7.8],
    soils: ["loamy", "alluvial", "clay", "black"],
    n: 120,
    p: 60,
    k: 40,
    durationDays: 130,
    waterMmPerSeason: 450,
    yieldTonPerHa: 3.8,
    pricePerTon: 250,
    costPerHa: 480,
    difficulty: 2,
    diseaseResistance: 65,
    marketDemand: 90,
    exportDemand: 65,
    carbonPerHa: 1.6,
    nitrogenFixing: false,
    plantingMonths: [10, 11, 12],
    diseases: [
      {
        name: "Yellow rust",
        trigger: "cool",
        symptoms: "Yellow pustules in stripes along leaf veins.",
        prevention: "Resistant cultivars, timely sowing.",
        treatment: "Propiconazole spray at first appearance.",
      },
    ],
    pests: ["Aphids", "Termites"],
    rotateAfter: ["Rice", "Soybean"],
    rotateBefore: ["Maize", "Green gram"],
    irrigation: "Sprinkler / limited flood (5-6 irrigations)",
    notes: "Cool grain-filling weather is the single biggest yield driver.",
  },
  {
    id: "maize",
    name: "Maize",
    emoji: "🌽",
    category: "Cereal",
    tempRange: [18, 33],
    humidityRange: [45, 85],
    rainRange: [450, 1200],
    phRange: [5.5, 7.5],
    soils: ["loamy", "alluvial", "red", "black", "sandy"],
    n: 130,
    p: 60,
    k: 50,
    durationDays: 105,
    waterMmPerSeason: 550,
    yieldTonPerHa: 6.2,
    pricePerTon: 210,
    costPerHa: 470,
    difficulty: 2,
    diseaseResistance: 70,
    marketDemand: 88,
    exportDemand: 60,
    carbonPerHa: 1.8,
    nitrogenFixing: false,
    plantingMonths: [3, 4, 5, 6, 9],
    diseases: [
      {
        name: "Turcicum leaf blight",
        trigger: "humid",
        symptoms: "Long cigar-shaped grey-green lesions.",
        prevention: "Crop rotation, residue removal.",
        treatment: "Mancozeb spray at 10-day intervals.",
      },
    ],
    pests: ["Fall armyworm", "Stem borer"],
    rotateAfter: ["Soybean", "Cowpea"],
    rotateBefore: ["Wheat", "Chickpea"],
    irrigation: "Drip or furrow; critical at tasseling",
    notes: "Highly responsive to nitrogen and good drainage.",
  },
  {
    id: "soybean",
    name: "Soybean",
    emoji: "🫘",
    category: "Oilseed / Legume",
    tempRange: [18, 32],
    humidityRange: [50, 90],
    rainRange: [450, 1100],
    phRange: [6.0, 7.5],
    soils: ["black", "loamy", "alluvial", "red"],
    n: 25,
    p: 60,
    k: 40,
    durationDays: 100,
    waterMmPerSeason: 500,
    yieldTonPerHa: 2.6,
    pricePerTon: 450,
    costPerHa: 480,
    difficulty: 2,
    diseaseResistance: 68,
    marketDemand: 85,
    exportDemand: 82,
    carbonPerHa: 0.9,
    nitrogenFixing: true,
    plantingMonths: [5, 6, 7],
    diseases: [
      {
        name: "Rust",
        trigger: "humid",
        symptoms: "Reddish-brown pustules on lower leaf surface.",
        prevention: "Early maturing varieties, spacing for airflow.",
        treatment: "Hexaconazole spray.",
      },
    ],
    pests: ["Girdle beetle", "Semilooper"],
    rotateAfter: ["Wheat", "Maize"],
    rotateBefore: ["Wheat", "Mustard"],
    irrigation: "Rain-fed with 1-2 protective irrigations",
    notes: "Fixes 60-80 kg N/ha, excellent soil restorer.",
  },
  {
    id: "chickpea",
    name: "Chickpea",
    emoji: "🌱",
    category: "Pulse",
    tempRange: [10, 30],
    humidityRange: [30, 70],
    rainRange: [300, 650],
    phRange: [6.0, 8.5],
    soils: ["black", "loamy", "sandy", "red"],
    n: 20,
    p: 50,
    k: 30,
    durationDays: 110,
    waterMmPerSeason: 320,
    yieldTonPerHa: 1.9,
    pricePerTon: 620,
    costPerHa: 380,
    difficulty: 2,
    diseaseResistance: 60,
    marketDemand: 84,
    exportDemand: 72,
    carbonPerHa: 0.6,
    nitrogenFixing: true,
    plantingMonths: [10, 11],
    diseases: [
      {
        name: "Fusarium wilt",
        trigger: "dry",
        symptoms: "Sudden drooping, browning of vascular tissue.",
        prevention: "Wilt-resistant varieties, 3-year rotation.",
        treatment: "Seed treatment with Trichoderma viride.",
      },
    ],
    pests: ["Pod borer"],
    rotateAfter: ["Rice", "Maize"],
    rotateBefore: ["Cotton", "Maize"],
    irrigation: "Rain-fed / 1-2 light irrigations",
    notes: "Very low water footprint, ideal for residual-moisture farming.",
  },
  {
    id: "cotton",
    name: "Cotton",
    emoji: "🌿",
    category: "Fibre",
    tempRange: [21, 38],
    humidityRange: [40, 80],
    rainRange: [500, 1100],
    phRange: [5.8, 8.2],
    soils: ["black", "loamy", "alluvial", "red"],
    n: 120,
    p: 60,
    k: 60,
    durationDays: 170,
    waterMmPerSeason: 800,
    yieldTonPerHa: 2.2,
    pricePerTon: 1500,
    costPerHa: 1250,
    difficulty: 4,
    diseaseResistance: 45,
    marketDemand: 80,
    exportDemand: 88,
    carbonPerHa: 2.4,
    nitrogenFixing: false,
    plantingMonths: [4, 5, 6],
    diseases: [
      {
        name: "Cotton leaf curl virus",
        trigger: "hot",
        symptoms: "Upward curling, thickened veins, stunting.",
        prevention: "Whitefly control, resistant hybrids.",
        treatment: "Manage vector with imidacloprid; rogue infected plants.",
      },
    ],
    pests: ["Pink bollworm", "Whitefly", "Jassids"],
    rotateAfter: ["Chickpea", "Green gram"],
    rotateBefore: ["Wheat", "Chickpea"],
    irrigation: "Drip strongly recommended",
    notes: "High input cost and pest pressure, but strong export value.",
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    emoji: "🎋",
    category: "Cash crop",
    tempRange: [21, 38],
    humidityRange: [55, 90],
    rainRange: [1100, 2500],
    phRange: [6.0, 7.8],
    soils: ["alluvial", "loamy", "clay", "black"],
    n: 250,
    p: 80,
    k: 90,
    durationDays: 330,
    waterMmPerSeason: 1800,
    yieldTonPerHa: 75,
    pricePerTon: 38,
    costPerHa: 1900,
    difficulty: 4,
    diseaseResistance: 58,
    marketDemand: 78,
    exportDemand: 45,
    carbonPerHa: 3.6,
    nitrogenFixing: false,
    plantingMonths: [1, 2, 10, 11],
    diseases: [
      {
        name: "Red rot",
        trigger: "wet",
        symptoms: "Red internal discolouration with white patches, alcohol smell.",
        prevention: "Disease-free setts, hot water treatment.",
        treatment: "Remove clumps; carbendazim sett dip.",
      },
    ],
    pests: ["Early shoot borer", "Pyrilla"],
    rotateAfter: ["Green gram", "Potato"],
    rotateBefore: ["Wheat", "Green gram"],
    irrigation: "Drip / furrow, very high demand",
    notes: "Only viable where water is assured for 10-12 months.",
  },
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    category: "Vegetable",
    tempRange: [15, 32],
    humidityRange: [45, 80],
    rainRange: [350, 800],
    phRange: [6.0, 7.2],
    soils: ["loamy", "red", "alluvial", "sandy"],
    n: 110,
    p: 80,
    k: 100,
    durationDays: 95,
    waterMmPerSeason: 480,
    yieldTonPerHa: 32,
    pricePerTon: 240,
    costPerHa: 1600,
    difficulty: 4,
    diseaseResistance: 40,
    marketDemand: 90,
    exportDemand: 50,
    carbonPerHa: 1.4,
    nitrogenFixing: false,
    plantingMonths: [1, 2, 6, 7, 9, 10],
    diseases: [
      {
        name: "Early blight",
        trigger: "humid",
        symptoms: "Concentric-ringed brown spots on older leaves.",
        prevention: "Mulching, staking, drip irrigation.",
        treatment: "Chlorothalonil or mancozeb every 10 days.",
      },
      {
        name: "Leaf curl virus",
        trigger: "hot",
        symptoms: "Curled, leathery leaves and stunted growth.",
        prevention: "Insect-proof nursery, whitefly nets.",
        treatment: "Vector control; remove infected plants.",
      },
    ],
    pests: ["Whitefly", "Fruit borer"],
    rotateAfter: ["Maize", "Cowpea"],
    rotateBefore: ["Onion", "Green gram"],
    irrigation: "Drip with mulch",
    notes: "High margin but price-volatile and disease sensitive.",
  },
  {
    id: "potato",
    name: "Potato",
    emoji: "🥔",
    category: "Vegetable",
    tempRange: [8, 25],
    humidityRange: [50, 85],
    rainRange: [350, 750],
    phRange: [5.0, 6.8],
    soils: ["loamy", "sandy", "alluvial", "silt"],
    n: 150,
    p: 80,
    k: 120,
    durationDays: 95,
    waterMmPerSeason: 500,
    yieldTonPerHa: 25,
    pricePerTon: 200,
    costPerHa: 1500,
    difficulty: 3,
    diseaseResistance: 45,
    marketDemand: 88,
    exportDemand: 55,
    carbonPerHa: 1.5,
    nitrogenFixing: false,
    plantingMonths: [10, 11, 12],
    diseases: [
      {
        name: "Late blight",
        trigger: "cool-humid",
        symptoms: "Water-soaked black lesions, white mould on leaf underside.",
        prevention: "Certified seed, ridging, forecast-based sprays.",
        treatment: "Metalaxyl + mancozeb on first alert.",
      },
    ],
    pests: ["Aphids", "Cutworm"],
    rotateAfter: ["Maize", "Rice"],
    rotateBefore: ["Green gram", "Maize"],
    irrigation: "Light frequent furrow or sprinkler",
    notes: "Needs cool nights below 20°C for tuber bulking.",
  },
  {
    id: "groundnut",
    name: "Groundnut",
    emoji: "🥜",
    category: "Oilseed / Legume",
    tempRange: [20, 35],
    humidityRange: [40, 80],
    rainRange: [450, 1000],
    phRange: [6.0, 7.5],
    soils: ["sandy", "red", "loamy", "laterite"],
    n: 25,
    p: 50,
    k: 40,
    durationDays: 110,
    waterMmPerSeason: 520,
    yieldTonPerHa: 2.3,
    pricePerTon: 700,
    costPerHa: 620,
    difficulty: 2,
    diseaseResistance: 62,
    marketDemand: 82,
    exportDemand: 75,
    carbonPerHa: 0.8,
    nitrogenFixing: true,
    plantingMonths: [5, 6, 11, 12],
    diseases: [
      {
        name: "Tikka leaf spot",
        trigger: "humid",
        symptoms: "Dark circular spots with yellow halo.",
        prevention: "Rotation, resistant varieties.",
        treatment: "Carbendazim + mancozeb spray.",
      },
    ],
    pests: ["Leaf miner", "White grub"],
    rotateAfter: ["Sorghum", "Maize"],
    rotateBefore: ["Wheat", "Cotton"],
    irrigation: "Sprinkler; critical at pegging",
    notes: "Prefers light, well-drained soils with gypsum at pegging.",
  },
  {
    id: "millet",
    name: "Pearl Millet",
    emoji: "🌾",
    category: "Millet",
    tempRange: [22, 42],
    humidityRange: [20, 70],
    rainRange: [200, 700],
    phRange: [5.5, 8.5],
    soils: ["sandy", "red", "laterite", "loamy"],
    n: 60,
    p: 30,
    k: 30,
    durationDays: 85,
    waterMmPerSeason: 300,
    yieldTonPerHa: 2.1,
    pricePerTon: 300,
    costPerHa: 260,
    difficulty: 1,
    diseaseResistance: 80,
    marketDemand: 70,
    exportDemand: 48,
    carbonPerHa: 0.5,
    nitrogenFixing: false,
    plantingMonths: [6, 7],
    diseases: [
      {
        name: "Downy mildew",
        trigger: "humid",
        symptoms: "Chlorotic streaks, green ear malformation.",
        prevention: "Seed treatment, resistant hybrids.",
        treatment: "Metalaxyl seed dressing.",
      },
    ],
    pests: ["Shoot fly"],
    rotateAfter: ["Cowpea", "Groundnut"],
    rotateBefore: ["Chickpea", "Mustard"],
    irrigation: "Rain-fed",
    notes: "Best climate-resilient choice for hot, dry, low-input land.",
  },
  {
    id: "sorghum",
    name: "Sorghum",
    emoji: "🌾",
    category: "Millet",
    tempRange: [20, 40],
    humidityRange: [25, 75],
    rainRange: [300, 800],
    phRange: [5.5, 8.5],
    soils: ["black", "red", "loamy", "sandy"],
    n: 80,
    p: 40,
    k: 40,
    durationDays: 110,
    waterMmPerSeason: 400,
    yieldTonPerHa: 3.0,
    pricePerTon: 260,
    costPerHa: 300,
    difficulty: 1,
    diseaseResistance: 78,
    marketDemand: 68,
    exportDemand: 42,
    carbonPerHa: 0.7,
    nitrogenFixing: false,
    plantingMonths: [6, 7, 9, 10],
    diseases: [
      {
        name: "Grain mould",
        trigger: "wet",
        symptoms: "Discoloured, fungus-covered grain at maturity.",
        prevention: "Avoid rain at grain-fill, tight-panicle types.",
        treatment: "Timely harvest and rapid drying.",
      },
    ],
    pests: ["Shoot fly", "Midge"],
    rotateAfter: ["Green gram", "Groundnut"],
    rotateBefore: ["Chickpea", "Cotton"],
    irrigation: "Rain-fed with one protective irrigation",
    notes: "Dual purpose grain plus fodder value.",
  },
  {
    id: "mustard",
    name: "Mustard",
    emoji: "🌼",
    category: "Oilseed",
    tempRange: [8, 27],
    humidityRange: [35, 70],
    rainRange: [250, 600],
    phRange: [6.0, 8.0],
    soils: ["loamy", "alluvial", "sandy", "black"],
    n: 80,
    p: 40,
    k: 40,
    durationDays: 120,
    waterMmPerSeason: 300,
    yieldTonPerHa: 1.6,
    pricePerTon: 620,
    costPerHa: 330,
    difficulty: 1,
    diseaseResistance: 66,
    marketDemand: 80,
    exportDemand: 52,
    carbonPerHa: 0.7,
    nitrogenFixing: false,
    plantingMonths: [10, 11],
    diseases: [
      {
        name: "White rust",
        trigger: "cool-humid",
        symptoms: "White raised pustules on leaf underside.",
        prevention: "Early sowing, resistant varieties.",
        treatment: "Metalaxyl-mancozeb spray.",
      },
    ],
    pests: ["Mustard aphid"],
    rotateAfter: ["Rice", "Maize"],
    rotateBefore: ["Green gram", "Maize"],
    irrigation: "1-2 irrigations",
    notes: "Excellent low-water rabi option with sulphur response.",
  },
  {
    id: "greengram",
    name: "Green Gram",
    emoji: "🫛",
    category: "Pulse",
    tempRange: [22, 38],
    humidityRange: [40, 85],
    rainRange: [300, 800],
    phRange: [6.0, 7.8],
    soils: ["loamy", "sandy", "red", "alluvial", "black"],
    n: 20,
    p: 40,
    k: 20,
    durationDays: 65,
    waterMmPerSeason: 280,
    yieldTonPerHa: 1.1,
    pricePerTon: 900,
    costPerHa: 300,
    difficulty: 1,
    diseaseResistance: 64,
    marketDemand: 83,
    exportDemand: 60,
    carbonPerHa: 0.4,
    nitrogenFixing: true,
    plantingMonths: [3, 4, 6, 7],
    diseases: [
      {
        name: "Yellow mosaic virus",
        trigger: "hot",
        symptoms: "Bright yellow mottling of leaves.",
        prevention: "Resistant varieties, whitefly control.",
        treatment: "Vector management; remove infected plants.",
      },
    ],
    pests: ["Whitefly", "Thrips"],
    rotateAfter: ["Wheat", "Rice"],
    rotateBefore: ["Rice", "Wheat"],
    irrigation: "Rain-fed / 1 irrigation",
    notes: "65-day catch crop that leaves nitrogen behind.",
  },
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    category: "Horticulture",
    tempRange: [20, 35],
    humidityRange: [60, 95],
    rainRange: [1000, 2500],
    phRange: [5.5, 7.5],
    soils: ["alluvial", "loamy", "clay", "red"],
    n: 200,
    p: 60,
    k: 300,
    durationDays: 330,
    waterMmPerSeason: 1800,
    yieldTonPerHa: 55,
    pricePerTon: 300,
    costPerHa: 3800,
    difficulty: 4,
    diseaseResistance: 42,
    marketDemand: 86,
    exportDemand: 78,
    carbonPerHa: 2.1,
    nitrogenFixing: false,
    plantingMonths: [2, 3, 6, 7],
    diseases: [
      {
        name: "Panama wilt",
        trigger: "wet",
        symptoms: "Yellowing of older leaves, pseudostem splitting.",
        prevention: "Tissue-culture plants, resistant clones.",
        treatment: "Carbendazim drench; avoid replanting infected blocks.",
      },
    ],
    pests: ["Rhizome weevil", "Nematodes"],
    rotateAfter: ["Green gram", "Maize"],
    rotateBefore: ["Legumes"],
    irrigation: "Drip with fertigation",
    notes: "Capital-intensive but very high gross returns per hectare.",
  },
  {
    id: "onion",
    name: "Onion",
    emoji: "🧅",
    category: "Vegetable",
    tempRange: [13, 30],
    humidityRange: [40, 75],
    rainRange: [300, 700],
    phRange: [6.0, 7.5],
    soils: ["loamy", "alluvial", "red", "silt"],
    n: 110,
    p: 60,
    k: 80,
    durationDays: 120,
    waterMmPerSeason: 450,
    yieldTonPerHa: 22,
    pricePerTon: 220,
    costPerHa: 1300,
    difficulty: 3,
    diseaseResistance: 52,
    marketDemand: 89,
    exportDemand: 74,
    carbonPerHa: 1.2,
    nitrogenFixing: false,
    plantingMonths: [5, 6, 10, 11],
    diseases: [
      {
        name: "Purple blotch",
        trigger: "humid",
        symptoms: "Purple centred lesions on leaves and stalks.",
        prevention: "Wider spacing, avoid overhead watering.",
        treatment: "Mancozeb with sticker every 10-12 days.",
      },
    ],
    pests: ["Thrips"],
    rotateAfter: ["Maize", "Green gram"],
    rotateBefore: ["Maize", "Cowpea"],
    irrigation: "Drip / sprinkler, stop 15 days before harvest",
    notes: "Storage life makes it a good price-arbitrage crop.",
  },
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
