import type { CropProfile } from "./types";

/**
 * Extended agronomic profile per crop: optimal (not just tolerable) ranges,
 * Indian season flags, stress tolerances and sowing/harvest windows.
 * Values follow ICAR / FAO extension guidance.
 */
export const CROP_PROFILES: Record<string, CropProfile> = {
  rice: {
    scientificName: "Oryza sativa",
    seasons: { kharif: true, rabi: false, zaid: false },
    tempOptimal: [25, 32],
    rainfallOptimal: 1500,
    phOptimal: 6.5,
    organicMatterReq: 1.5,
    ecTolerance: 3.0,
    soilTexturePref: "Clay to clay loam",
    waterRequirement: "high",
    sowingWindow: "June – July",
    harvestWindow: "October – November",
    droughtTolerance: "low",
    salinityTolerance: "medium",
    waterloggingTolerance: "high",
  },
  wheat: {
    scientificName: "Triticum aestivum",
    seasons: { kharif: false, rabi: true, zaid: false },
    tempOptimal: [16, 24],
    rainfallOptimal: 600,
    phOptimal: 6.8,
    organicMatterReq: 1.5,
    ecTolerance: 6.0,
    soilTexturePref: "Loam to clay loam",
    waterRequirement: "medium",
    sowingWindow: "November – December",
    harvestWindow: "March – April",
    droughtTolerance: "medium",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  maize: {
    scientificName: "Zea mays",
    seasons: { kharif: true, rabi: true, zaid: true },
    tempOptimal: [21, 30],
    rainfallOptimal: 750,
    phOptimal: 6.5,
    organicMatterReq: 1.5,
    ecTolerance: 1.7,
    soilTexturePref: "Well-drained sandy loam to loam",
    waterRequirement: "medium",
    sowingWindow: "June – July (kharif), Oct – Nov (rabi)",
    harvestWindow: "September – October",
    droughtTolerance: "medium",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
  soybean: {
    scientificName: "Glycine max",
    seasons: { kharif: true, rabi: false, zaid: false },
    tempOptimal: [26, 32],
    rainfallOptimal: 800,
    phOptimal: 6.5,
    organicMatterReq: 1.0,
    ecTolerance: 5.0,
    soilTexturePref: "Sandy loam to clay loam",
    waterRequirement: "medium",
    sowingWindow: "June – July",
    harvestWindow: "October – November",
    droughtTolerance: "medium",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  chickpea: {
    scientificName: "Cicer arietinum",
    seasons: { kharif: false, rabi: true, zaid: false },
    tempOptimal: [18, 26],
    rainfallOptimal: 450,
    phOptimal: 7.0,
    organicMatterReq: 0.8,
    ecTolerance: 4.0,
    soilTexturePref: "Black soil / well-drained loam",
    waterRequirement: "low",
    sowingWindow: "October – November",
    harvestWindow: "February – March",
    droughtTolerance: "high",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  cotton: {
    scientificName: "Gossypium hirsutum",
    seasons: { kharif: true, rabi: false, zaid: false },
    tempOptimal: [27, 32],
    rainfallOptimal: 850,
    phOptimal: 7.0,
    organicMatterReq: 1.0,
    ecTolerance: 7.7,
    soilTexturePref: "Black cotton soil",
    waterRequirement: "medium",
    sowingWindow: "April – May",
    harvestWindow: "October – February",
    droughtTolerance: "high",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  sugarcane: {
    scientificName: "Saccharum officinarum",
    seasons: { kharif: true, rabi: false, zaid: true },
    tempOptimal: [25, 32],
    rainfallOptimal: 1500,
    phOptimal: 6.5,
    organicMatterReq: 2.0,
    ecTolerance: 4.0,
    soilTexturePref: "Loam",
    waterRequirement: "high",
    sowingWindow: "February – March",
    harvestWindow: "November – March",
    droughtTolerance: "medium",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  tomato: {
    scientificName: "Solanum lycopersicum",
    seasons: { kharif: true, rabi: true, zaid: true },
    tempOptimal: [21, 28],
    rainfallOptimal: 600,
    phOptimal: 6.5,
    organicMatterReq: 2.0,
    ecTolerance: 2.5,
    soilTexturePref: "Sandy loam to clay loam",
    waterRequirement: "medium",
    sowingWindow: "Year-round (staggered)",
    harvestWindow: "Year-round",
    droughtTolerance: "medium",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  potato: {
    scientificName: "Solanum tuberosum",
    seasons: { kharif: false, rabi: true, zaid: false },
    tempOptimal: [18, 22],
    rainfallOptimal: 600,
    phOptimal: 6.0,
    organicMatterReq: 2.0,
    ecTolerance: 2.0,
    soilTexturePref: "Sandy loam",
    waterRequirement: "medium",
    sowingWindow: "October – November",
    harvestWindow: "January – February",
    droughtTolerance: "low",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
  groundnut: {
    scientificName: "Arachis hypogaea",
    seasons: { kharif: true, rabi: true, zaid: false },
    tempOptimal: [25, 32],
    rainfallOptimal: 700,
    phOptimal: 6.5,
    organicMatterReq: 1.0,
    ecTolerance: 3.2,
    soilTexturePref: "Light sandy loam / red soil",
    waterRequirement: "medium",
    sowingWindow: "June – July",
    harvestWindow: "October – November",
    droughtTolerance: "high",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
  millet: {
    scientificName: "Pennisetum glaucum",
    seasons: { kharif: true, rabi: false, zaid: true },
    tempOptimal: [28, 35],
    rainfallOptimal: 450,
    phOptimal: 7.0,
    organicMatterReq: 0.5,
    ecTolerance: 8.0,
    soilTexturePref: "Sandy / light red soil",
    waterRequirement: "low",
    sowingWindow: "June – July",
    harvestWindow: "September – October",
    droughtTolerance: "high",
    salinityTolerance: "high",
    waterloggingTolerance: "low",
  },
  sorghum: {
    scientificName: "Sorghum bicolor",
    seasons: { kharif: true, rabi: true, zaid: false },
    tempOptimal: [26, 33],
    rainfallOptimal: 550,
    phOptimal: 6.8,
    organicMatterReq: 0.6,
    ecTolerance: 6.8,
    soilTexturePref: "Black or red loam",
    waterRequirement: "low",
    sowingWindow: "June – July (kharif), Sep – Oct (rabi)",
    harvestWindow: "October – February",
    droughtTolerance: "high",
    salinityTolerance: "high",
    waterloggingTolerance: "low",
  },
  mustard: {
    scientificName: "Brassica juncea",
    seasons: { kharif: false, rabi: true, zaid: false },
    tempOptimal: [15, 24],
    rainfallOptimal: 400,
    phOptimal: 7.0,
    organicMatterReq: 0.8,
    ecTolerance: 5.5,
    soilTexturePref: "Loam to sandy loam",
    waterRequirement: "low",
    sowingWindow: "October – November",
    harvestWindow: "February – March",
    droughtTolerance: "high",
    salinityTolerance: "medium",
    waterloggingTolerance: "low",
  },
  greengram: {
    scientificName: "Vigna radiata",
    seasons: { kharif: true, rabi: false, zaid: true },
    tempOptimal: [27, 34],
    rainfallOptimal: 500,
    phOptimal: 6.8,
    organicMatterReq: 0.8,
    ecTolerance: 3.5,
    soilTexturePref: "Sandy loam to loam",
    waterRequirement: "low",
    sowingWindow: "March – April (zaid), June – July (kharif)",
    harvestWindow: "60–70 days after sowing",
    droughtTolerance: "high",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
  banana: {
    scientificName: "Musa acuminata",
    seasons: { kharif: true, rabi: false, zaid: true },
    tempOptimal: [25, 32],
    rainfallOptimal: 1700,
    phOptimal: 6.5,
    organicMatterReq: 2.5,
    ecTolerance: 1.5,
    soilTexturePref: "Deep alluvial loam",
    waterRequirement: "high",
    sowingWindow: "February – March, June – July",
    harvestWindow: "11–13 months after planting",
    droughtTolerance: "low",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
  onion: {
    scientificName: "Allium cepa",
    seasons: { kharif: true, rabi: true, zaid: false },
    tempOptimal: [16, 25],
    rainfallOptimal: 500,
    phOptimal: 6.5,
    organicMatterReq: 1.5,
    ecTolerance: 2.0,
    soilTexturePref: "Sandy loam to silt loam",
    waterRequirement: "medium",
    sowingWindow: "June – July (kharif), Nov – Dec (rabi)",
    harvestWindow: "November – December",
    droughtTolerance: "low",
    salinityTolerance: "low",
    waterloggingTolerance: "low",
  },
};

export function cropProfile(id: string): CropProfile | undefined {
  return CROP_PROFILES[id];
}

/** Season a planting month falls into, Indian cropping calendar. */
export function seasonOfMonth(month: number): "kharif" | "rabi" | "zaid" {
  if (month >= 6 && month <= 9) return "kharif";
  if (month >= 10 || month <= 2) return "rabi";
  return "zaid";
}
